# Generated by Django 2.2.5 on 2019-09-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
